/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'shipping' : null } |
  { 'pickedUp' : null } |
  { 'confirmed' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface Device {
  'active' : boolean,
  'activatedAt' : bigint,
  'name' : string,
  'role' : DeviceRole,
  'tenantId' : TenantId,
  'restaurantId' : string,
  'deviceId' : string,
  'phone' : string,
}
export interface DeviceEntry { 'device' : Device, 'deviceId' : string }
export type DeviceId = string;
export type DeviceRole = { 'accounting' : null } |
  { 'paymentQueue' : null } |
  { 'admin' : null } |
  { 'salesPromoReporting' : null } |
  { 'cashier' : null } |
  { 'tenantAdmin' : null } |
  { 'driver' : null };
export interface DiscountTier {
  'discountAmount' : bigint,
  'minOrderValue' : bigint,
}
export type Email = string;
export type EnterpriseRole = { 'accounting' : null } |
  { 'paymentQueue' : null } |
  { 'salesPromoReporting' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type Hmac = string;
export type InvoiceStatus = { 'none' : null } |
  { 'invoiced' : null } |
  { 'failed' : null };
export interface MenuEntry { 'itemId' : string, 'menu' : MenuItem }
export interface MenuItem {
  'itemId' : string,
  'name' : string,
  'tenantId' : TenantId,
  'visible' : boolean,
  'category' : string,
  'image' : Uint8Array,
  'price' : bigint,
  'vatRate' : bigint,
  'unitName' : string,
}
export interface Order {
  'paymentStatus' : PaymentStatus,
  'cusTaxCode' : string,
  'cusName' : string,
  'createdAt' : bigint,
  'taxTotal' : bigint,
  'ahamoveOrderId' : string,
  'tingeeQrCode' : string,
  'shippingFee' : bigint,
  'invoiceId' : string,
  'sharedLink' : string,
  'cusPhone' : string,
  'tenantId' : TenantId,
  'orderId' : string,
  'restaurantId' : string,
  'updatedAt' : bigint,
  'bookingStatus' : BookingStatus,
  'receiverEmail' : string,
  'pickupCode' : string,
  'expireAt' : [] | [bigint],
  'kmDiscountAmount' : bigint,
  'pdfUrl' : string,
  'tingeeQrId' : string,
  'goodsAmount' : bigint,
  'items' : Array<OrderItem>,
  'voucherDiscountAmount' : bigint,
  'amount' : bigint,
  'paymentVerificationImage' : string,
  'cusAddress' : string,
  'invoiceStatus' : InvoiceStatus,
  'billId' : [] | [string],
  'qrCode' : [] | [string],
}
export interface OrderEntry { 'order' : Order, 'orderId' : OrderId }
export type OrderId = string;
export interface OrderItem {
  'itemId' : string,
  'name' : string,
  'quantity' : bigint,
  'price' : bigint,
  'vatRate' : bigint,
  'unitName' : string,
}
export interface OrderStatus {
  'paymentStatus' : PaymentStatus,
  'tingeeQrCode' : string,
  'invoiceId' : string,
  'sharedLink' : string,
  'bookingStatus' : BookingStatus,
  'pdfUrl' : string,
  'tingeeQrId' : string,
  'invoiceStatus' : InvoiceStatus,
}
export type PaymentStatus = { 'expired' : null } |
  { 'paid' : null } |
  { 'refunded' : null } |
  { 'unpaid' : null };
export interface PendingActivation {
  'expiresAt' : bigint,
  'code' : string,
  'createdAt' : bigint,
  'role' : DeviceRole,
  'used' : boolean,
  'tenantId' : TenantId,
  'restaurantId' : string,
}
export interface PendingActivationEntry {
  'code' : string,
  'activation' : PendingActivation,
}
export interface Promotion {
  'tiers' : Array<DiscountTier>,
  'active' : boolean,
  'endDate' : string,
  'timeSlots' : Array<TimeSlot>,
  'enabledOnline' : boolean,
  'code' : string,
  'name' : string,
  'daysOfWeek' : Array<boolean>,
  'tenantId' : TenantId,
  'enabledCounter' : boolean,
  'dailyOrderLimit' : bigint,
  'perCustomerDailyLimit' : bigint,
  'termsUrl' : string,
  'startDate' : string,
}
export interface RegistrationPromo {
  'active' : boolean,
  'endDate' : string,
  'code' : string,
  'name' : string,
  'voucherValidDays' : bigint,
  'tenantId' : TenantId,
  'voucherValue' : bigint,
  'termsUrl' : string,
  'startDate' : string,
}
export interface Restaurant {
  'lat' : number,
  'lng' : number,
  'name' : string,
  'tenantId' : TenantId,
  'restaurantId' : string,
  'address' : string,
  'visible' : boolean,
  'phone' : string,
}
export interface RestaurantEntry {
  'restaurantId' : string,
  'restaurant' : Restaurant,
}
export type RestaurantId = string;
export interface RestaurantMenuOverrideEntry {
  'restaurantId' : string,
  'overrides' : Array<[string, bigint]>,
}
export type Result = { 'ok' : Order } |
  { 'err' : string };
export type Result_1 = { 'ok' : SalesPromo } |
  { 'err' : string };
export type Result_10 = { 'ok' : Array<RegistrationPromo> } |
  { 'err' : string };
export type Result_11 = { 'ok' : Array<Promotion> } |
  { 'err' : string };
export type Result_12 = { 'ok' : [] | [Voucher] } |
  { 'err' : string };
export type Result_13 = { 'ok' : boolean } |
  { 'err' : string };
export type Result_14 = { 'ok' : OrderStatus } |
  { 'err' : string };
export type Result_15 = { 'ok' : PendingActivation } |
  { 'err' : string };
export type Result_16 = {
    'ok' : { 'discountAmount' : bigint, 'promotionCode' : string }
  } |
  { 'err' : string };
export type Result_18 = { 'ok' : null } |
  { 'err' : Error };
export type Result_2 = { 'ok' : Restaurant } |
  { 'err' : string };
export type Result_3 = { 'ok' : RegistrationPromo } |
  { 'err' : string };
export type Result_4 = { 'ok' : Promotion } |
  { 'err' : string };
export type Result_5 = { 'ok' : MenuItem } |
  { 'err' : string };
export type Result_6 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_7 = { 'ok' : null } |
  { 'err' : string };
export type Result_8 = { 'ok' : Device } |
  { 'err' : string };
export type Result_9 = { 'ok' : Array<SalesPromo> } |
  { 'err' : string };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface SalesPromo {
  'active' : boolean,
  'endDate' : string,
  'code' : string,
  'name' : string,
  'voucherValidDays' : bigint,
  'tenantId' : TenantId,
  'weeklyTiers' : Array<SalesTier>,
  'enabledCounter' : boolean,
  'monthlyTiers' : Array<SalesTier>,
  'termsUrl' : string,
  'startDate' : string,
}
export interface SalesTier { 'minSales' : bigint, 'voucherValue' : bigint }
export type SendCodeResult = { 'ok' : null } |
  { 'err' : string };
export interface StoreHours {
  'closeMinute' : bigint,
  'closeHour' : bigint,
  'openMinute' : bigint,
  'openHour' : bigint,
}
export interface Tenant {
  'active' : boolean,
  'name' : string,
  'createdAt' : Timestamp,
  'slug' : string,
  'tenantId' : TenantId,
  'updatedAt' : Timestamp,
  'logoUrl' : string,
  'address' : string,
  'companyName' : string,
  'phone' : string,
  'taxCode' : string,
  'brandColor' : string,
}
export type TenantId = string;
export interface TimeSlot {
  'durationMinutes' : bigint,
  'startMinute' : bigint,
  'startHour' : bigint,
}
export type Timestamp = bigint;
export interface UpgradeState {
  'menus' : Array<MenuEntry>,
  'orders' : Array<OrderEntry>,
  'restaurants' : Array<RestaurantEntry>,
  'restaurantMenuOverrides' : Array<RestaurantMenuOverrideEntry>,
  'devices' : Array<DeviceEntry>,
  'pendingActivations' : Array<PendingActivationEntry>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export type VerifyResult = { 'ok' : null } |
  { 'err' : string };
export interface Voucher {
  'endDate' : string,
  'value' : bigint,
  'code' : string,
  'used' : boolean,
  'email' : string,
  'tenantId' : TenantId,
  'programCode' : string,
  'issuedAt' : bigint,
  'startDate' : string,
}
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_18>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'activateDevice' : ActorMethod<[string, DeviceId, string, string], Result_8>,
  'addItem' : ActorMethod<
    [
      TenantId,
      DeviceId,
      string,
      string,
      bigint,
      string,
      bigint,
      string,
      Uint8Array,
    ],
    Result_5
  >,
  'addRestaurant' : ActorMethod<
    [TenantId, DeviceId, string, string, string, string, number, number],
    Result_2
  >,
  'applyPromotion' : ActorMethod<[TenantId, string, bigint, Hmac], Result_16>,
  'applyPromotionCounter' : ActorMethod<[TenantId, bigint, Hmac], Result_16>,
  'applyVoucher' : ActorMethod<
    [TenantId, string, string, bigint, Hmac],
    Result_6
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'callerHasEnterpriseRole' : ActorMethod<
    [DeviceId, TenantId, EnterpriseRole],
    boolean
  >,
  'cancelOrder' : ActorMethod<[string, string], Result>,
  'changeOrderRestaurant' : ActorMethod<[string, string, string], Result>,
  'claimOrderEmail' : ActorMethod<[string, string, string], Result>,
  'cleanupExpiredActivations' : ActorMethod<[], bigint>,
  'cleanupOrderByDevice' : ActorMethod<[string, string, string], Result>,
  'countVouchersByProgram' : ActorMethod<[string, string], bigint>,
  'createOrder' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      Array<OrderItem>,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      string,
    ],
    Result
  >,
  'createPromotion' : ActorMethod<
    [
      TenantId,
      string,
      string,
      string,
      string,
      Array<boolean>,
      Array<TimeSlot>,
      bigint,
      bigint,
      Array<DiscountTier>,
      string,
    ],
    Result_4
  >,
  'createRegistrationPromo' : ActorMethod<
    [TenantId, string, string, string, string, bigint, bigint, string],
    Result_3
  >,
  'createSalesPromo' : ActorMethod<
    [
      TenantId,
      string,
      string,
      string,
      string,
      Array<SalesTier>,
      Array<SalesTier>,
      bigint,
      string,
    ],
    Result_1
  >,
  /**
   * / Tạo đối tác mới. Admin trung tâm only.
   */
  'createTenant' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    { 'ok' : Tenant } |
      { 'err' : string }
  >,
  'deactivateExpiredPromotions' : ActorMethod<[Hmac], Result_6>,
  'deleteItem' : ActorMethod<[TenantId, DeviceId, string], Result_7>,
  'deletePromotion' : ActorMethod<[TenantId, string, string], Result_7>,
  'deleteRegistrationPromo' : ActorMethod<[TenantId, string, string], Result_7>,
  'deleteRestaurant' : ActorMethod<[TenantId, DeviceId, string], Result_7>,
  'deleteSalesPromo' : ActorMethod<[TenantId, string, string], Result_7>,
  'execute' : ActorMethod<[string], Result__1>,
  'generateActivationCode' : ActorMethod<
    [TenantId, RestaurantId, DeviceRole, DeviceId],
    Result_15
  >,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Returns the canister's own id as text, so the VPS knows which canister
   * / it is talking to. `Principal.fromActor(Main)` resolves the actor's own
   * / canister principal at runtime (mo:core/IC.getCanisterId does not exist in
   * / core 2.6.1).
   */
  'getCanisterIdText' : ActorMethod<[], string>,
  'getCurrentPromotion' : ActorMethod<[TenantId], [] | [Promotion]>,
  'getCurrentRegistrationPromo' : ActorMethod<
    [TenantId],
    [] | [RegistrationPromo]
  >,
  'getCurrentSalesPromo' : ActorMethod<[TenantId], [] | [SalesPromo]>,
  'getItemImage' : ActorMethod<[string], [] | [Uint8Array]>,
  'getKmDailyCount' : ActorMethod<[TenantId, string], bigint>,
  'getKmUsageCount' : ActorMethod<[TenantId, string, string], bigint>,
  'getMenu' : ActorMethod<[TenantId], Array<MenuItem>>,
  'getMenuForRestaurant' : ActorMethod<[TenantId, string], Array<MenuItem>>,
  'getOrder' : ActorMethod<[string, string, string], Result>,
  'getOrderStatus' : ActorMethod<[string, string], Result_14>,
  'getOrdersByEmail' : ActorMethod<[string, string, string], Array<Order>>,
  /**
   * / Query: return the paymentMode for `tenantId` as its canonical Text
   * / ("driver" or "customer"). Public — no caller gating; the value is not
   * / sensitive. A tenant with no explicit config returns the default "driver".
   */
  'getPaymentMode' : ActorMethod<[TenantId], string>,
  'getPromotionByCode' : ActorMethod<[TenantId, string], [] | [Promotion]>,
  'getRestaurants' : ActorMethod<[TenantId], Array<Restaurant>>,
  /**
   * / Query: return the storeHours config for `tenantId`. Public — no caller
   * / gating; the value is not sensitive and the frontend needs it to render the
   * / open/close state on both the driver and customer flows. A tenant with no
   * / explicit config returns the default (00:00–23:59, always open).
   */
  'getStoreHours' : ActorMethod<[TenantId], StoreHours>,
  /**
   * / Lấy đối tác theo tenantId. Công khai.
   */
  'getTenant' : ActorMethod<[TenantId], [] | [Tenant]>,
  /**
   * / Lấy đối tác theo slug — frontend dùng để phân giải đối tác từ hostname
   * / subdomain hoặc tiền tố đường dẫn /<slug>. Công khai.
   */
  'getTenantBySlug' : ActorMethod<[string], [] | [Tenant]>,
  'getUpgradeState' : ActorMethod<[], UpgradeState>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isEmailVerified' : ActorMethod<[Email], boolean>,
  'isPromotionUsed' : ActorMethod<[TenantId, string, string], Result_13>,
  'isRegistrationPromoUsed' : ActorMethod<
    [TenantId, string, string],
    Result_13
  >,
  'isSalesPromoUsed' : ActorMethod<[TenantId, string, string], Result_13>,
  /**
   * / Query: return whether the store of `tenantId` is currently open based on
   * / the current time. Public — the frontend calls this on both the driver and
   * / customer flows to decide whether to block order placement and show a
   * / waiting screen instead of allowing item selection.
   */
  'isStoreOpen' : ActorMethod<[TenantId], boolean>,
  'issueInvoiceByDevice' : ActorMethod<
    [string, string, string, string, string],
    Result
  >,
  'issueSalesBonus' : ActorMethod<
    [TenantId, string, string, string, bigint, Hmac],
    Result_12
  >,
  'listDevicesByRestaurant' : ActorMethod<
    [TenantId, RestaurantId],
    Array<Device>
  >,
  'listDevicesByRole' : ActorMethod<[TenantId, DeviceRole], Array<Device>>,
  'listMenus' : ActorMethod<[TenantId], Array<MenuItem>>,
  'listMyVouchers' : ActorMethod<[TenantId, string], Array<Voucher>>,
  'listOrders' : ActorMethod<[string, string], Array<Order>>,
  /**
   * / Query: return today's paid orders for the driver pickup queue — orders with
   * / paymentStatus=#paid AND bookingStatus=#confirmed (not yet picked up),
   * / created today (UTC+7 day boundary, same day-retention logic as
   * / listPendingPaymentOrders). Admin sees the full records WITH PII;
   * / non-admin/anonymous callers (the driver pickup-queue flow) get the records
   * / with PII fields blanked, mirroring listPendingPaymentOrders gating.
   */
  'listPaidOrdersForPickup' : ActorMethod<[], Array<Order>>,
  'listPendingPaymentOrders' : ActorMethod<[string, string], Array<Order>>,
  'listPromotions' : ActorMethod<[TenantId, string], Result_11>,
  'listRegistrationPromos' : ActorMethod<[TenantId, string], Result_10>,
  'listRestaurants' : ActorMethod<[TenantId], Array<Restaurant>>,
  'listSalesPromos' : ActorMethod<[TenantId, string], Result_9>,
  /**
   * / Liệt kê đối tác. Công khai. activeOnly=true chỉ trả đối tác đang hoạt
   * / động (caller không phải admin luôn chỉ thấy đối tác đang hoạt động).
   */
  'listTenants' : ActorMethod<[boolean], Array<Tenant>>,
  'markPaymentExpired' : ActorMethod<[string, string], Result>,
  /**
   * / Admin/driver update: mark an order as #pickedUp (Tài xế đã nhận hàng).
   * / Only succeeds when the order is currently #confirmed AND #paid; this ends
   * / the order lifecycle in customer mode. Returns the updated order on
   * / success, or #err if the caller is not an admin/driver, the order does not
   * / exist, or the order is not in the required state.
   */
  'markPickedUp' : ActorMethod<[string], Result>,
  'pruneOldOrdersNow' : ActorMethod<[string], Result_6>,
  'restoreUpgradeState' : ActorMethod<[Uint8Array], boolean>,
  'revokeDevice' : ActorMethod<[TenantId, DeviceId, DeviceId], Result_8>,
  'schema' : ActorMethod<[], string>,
  'seedMenuItems' : ActorMethod<[TenantId, DeviceId], boolean>,
  'sendKmNotifyEmails' : ActorMethod<
    [Array<string>, string, string, Hmac],
    Result_7
  >,
  'sendVerificationCode' : ActorMethod<[Email], SendCodeResult>,
  'setItemVisible' : ActorMethod<
    [TenantId, DeviceId, string, boolean],
    Result_5
  >,
  /**
   * / Admin-only update: set the paymentMode for `tenantId` to "driver" or
   * / "customer". Rejects any other value with #err. Returns #ok on success,
   * / #err if the caller is not an admin or the value is invalid. Mirrors
   * / setVpsSecret in mixins/secret-api.mo.
   */
  'setPaymentMode' : ActorMethod<[TenantId, string], Result_7>,
  'setRestaurantPriceOverride' : ActorMethod<
    [TenantId, DeviceId, string, string, bigint],
    Result_7
  >,
  /**
   * / Admin-only update: set the store open/close hours for `tenantId`. Rejects
   * / any caller that is not an admin with #err. Returns #ok on success, #err if
   * / the caller is not an admin. Mirrors setPaymentMode in
   * / mixins/payment-mode-config-api.mo.
   */
  'setStoreHours' : ActorMethod<[TenantId, StoreHours], Result_7>,
  /**
   * / Bật/tắt đối tác. Admin trung tâm only.
   */
  'setTenantActive' : ActorMethod<
    [TenantId, boolean],
    { 'ok' : Tenant } |
      { 'err' : string }
  >,
  /**
   * / Admin-only. Rotates the VPS secret: current `vpsSecret` is moved into
   * / `vpsSecretPrevious` before `newSecret` is written to `vpsSecret`.
   * / Returns `#ok` on success, `#err` if the caller is not an admin.
   */
  'setVpsSecret' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'snapshotUpgradeState' : ActorMethod<[], Uint8Array>,
  'stopPromotion' : ActorMethod<[TenantId, string, string], Result_4>,
  'stopRegistrationPromo' : ActorMethod<[TenantId, string, string], Result_3>,
  'stopSalesPromo' : ActorMethod<[TenantId, string, string], Result_1>,
  'tryConsumeKmSlot' : ActorMethod<
    [TenantId, string, string, bigint, Hmac],
    Result_6
  >,
  'updateInvoiceStatus' : ActorMethod<
    [OrderId, InvoiceStatus, string, string, Hmac],
    Result
  >,
  'updateItem' : ActorMethod<
    [
      TenantId,
      DeviceId,
      string,
      string,
      bigint,
      string,
      bigint,
      string,
      Uint8Array,
      boolean,
    ],
    Result_5
  >,
  'updateOrderQr' : ActorMethod<
    [string, [] | [string], [] | [string], [] | [bigint], string],
    Result
  >,
  'updatePaymentStatus' : ActorMethod<[OrderId, PaymentStatus, Hmac], Result>,
  'updatePromotion' : ActorMethod<
    [
      TenantId,
      string,
      string,
      string,
      string,
      string,
      Array<boolean>,
      Array<TimeSlot>,
      bigint,
      bigint,
      Array<DiscountTier>,
      boolean,
      boolean,
      boolean,
      string,
    ],
    Result_4
  >,
  'updateRegistrationPromo' : ActorMethod<
    [
      TenantId,
      string,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      boolean,
      string,
    ],
    Result_3
  >,
  'updateRestaurant' : ActorMethod<
    [
      TenantId,
      DeviceId,
      string,
      string,
      string,
      string,
      boolean,
      number,
      number,
    ],
    Result_2
  >,
  'updateSalesPromo' : ActorMethod<
    [
      TenantId,
      string,
      string,
      string,
      string,
      string,
      Array<SalesTier>,
      Array<SalesTier>,
      bigint,
      boolean,
      boolean,
      string,
    ],
    Result_1
  >,
  'updateStatus' : ActorMethod<[OrderId, BookingStatus, Hmac], Result>,
  /**
   * / Cập nhật thông tin đối tác. Admin trung tâm only.
   */
  'updateTenant' : ActorMethod<
    [TenantId, string, string, string, string, string, string, string],
    { 'ok' : Tenant } |
      { 'err' : string }
  >,
  'verifyEmailCode' : ActorMethod<[string, Email, string], VerifyResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];