/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_18 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const DeviceId = IDL.Text;
export const DeviceRole = IDL.Variant({
  'accounting' : IDL.Null,
  'paymentQueue' : IDL.Null,
  'admin' : IDL.Null,
  'salesPromoReporting' : IDL.Null,
  'cashier' : IDL.Null,
  'tenantAdmin' : IDL.Null,
  'driver' : IDL.Null,
});
export const TenantId = IDL.Text;
export const Device = IDL.Record({
  'active' : IDL.Bool,
  'activatedAt' : IDL.Int,
  'name' : IDL.Text,
  'role' : DeviceRole,
  'tenantId' : TenantId,
  'restaurantId' : IDL.Text,
  'deviceId' : IDL.Text,
  'phone' : IDL.Text,
});
export const Result_8 = IDL.Variant({ 'ok' : Device, 'err' : IDL.Text });
export const MenuItem = IDL.Record({
  'itemId' : IDL.Text,
  'name' : IDL.Text,
  'tenantId' : TenantId,
  'visible' : IDL.Bool,
  'category' : IDL.Text,
  'image' : IDL.Vec(IDL.Nat8),
  'price' : IDL.Nat,
  'vatRate' : IDL.Nat,
  'unitName' : IDL.Text,
});
export const Result_5 = IDL.Variant({ 'ok' : MenuItem, 'err' : IDL.Text });
export const Restaurant = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'name' : IDL.Text,
  'tenantId' : TenantId,
  'restaurantId' : IDL.Text,
  'address' : IDL.Text,
  'visible' : IDL.Bool,
  'phone' : IDL.Text,
});
export const Result_2 = IDL.Variant({ 'ok' : Restaurant, 'err' : IDL.Text });
export const Hmac = IDL.Text;
export const Result_16 = IDL.Variant({
  'ok' : IDL.Record({ 'discountAmount' : IDL.Nat, 'promotionCode' : IDL.Text }),
  'err' : IDL.Text,
});
export const Result_6 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EnterpriseRole = IDL.Variant({
  'accounting' : IDL.Null,
  'paymentQueue' : IDL.Null,
  'salesPromoReporting' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'expired' : IDL.Null,
  'paid' : IDL.Null,
  'refunded' : IDL.Null,
  'unpaid' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'shipping' : IDL.Null,
  'pickedUp' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'itemId' : IDL.Text,
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'vatRate' : IDL.Nat,
  'unitName' : IDL.Text,
});
export const InvoiceStatus = IDL.Variant({
  'none' : IDL.Null,
  'invoiced' : IDL.Null,
  'failed' : IDL.Null,
});
export const Order = IDL.Record({
  'paymentStatus' : PaymentStatus,
  'cusTaxCode' : IDL.Text,
  'cusName' : IDL.Text,
  'createdAt' : IDL.Int,
  'taxTotal' : IDL.Nat,
  'ahamoveOrderId' : IDL.Text,
  'tingeeQrCode' : IDL.Text,
  'shippingFee' : IDL.Nat,
  'invoiceId' : IDL.Text,
  'sharedLink' : IDL.Text,
  'cusPhone' : IDL.Text,
  'tenantId' : TenantId,
  'orderId' : IDL.Text,
  'restaurantId' : IDL.Text,
  'updatedAt' : IDL.Int,
  'bookingStatus' : BookingStatus,
  'receiverEmail' : IDL.Text,
  'pickupCode' : IDL.Text,
  'expireAt' : IDL.Opt(IDL.Nat64),
  'kmDiscountAmount' : IDL.Nat,
  'pdfUrl' : IDL.Text,
  'tingeeQrId' : IDL.Text,
  'goodsAmount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
  'voucherDiscountAmount' : IDL.Nat,
  'amount' : IDL.Nat,
  'paymentVerificationImage' : IDL.Text,
  'cusAddress' : IDL.Text,
  'invoiceStatus' : InvoiceStatus,
  'billId' : IDL.Opt(IDL.Text),
  'qrCode' : IDL.Opt(IDL.Text),
});
export const Result = IDL.Variant({ 'ok' : Order, 'err' : IDL.Text });
export const TimeSlot = IDL.Record({
  'durationMinutes' : IDL.Nat,
  'startMinute' : IDL.Nat,
  'startHour' : IDL.Nat,
});
export const DiscountTier = IDL.Record({
  'discountAmount' : IDL.Nat,
  'minOrderValue' : IDL.Nat,
});
export const Promotion = IDL.Record({
  'tiers' : IDL.Vec(DiscountTier),
  'active' : IDL.Bool,
  'endDate' : IDL.Text,
  'timeSlots' : IDL.Vec(TimeSlot),
  'enabledOnline' : IDL.Bool,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'daysOfWeek' : IDL.Vec(IDL.Bool),
  'tenantId' : TenantId,
  'enabledCounter' : IDL.Bool,
  'dailyOrderLimit' : IDL.Nat,
  'perCustomerDailyLimit' : IDL.Nat,
  'termsUrl' : IDL.Text,
  'startDate' : IDL.Text,
});
export const Result_4 = IDL.Variant({ 'ok' : Promotion, 'err' : IDL.Text });
export const RegistrationPromo = IDL.Record({
  'active' : IDL.Bool,
  'endDate' : IDL.Text,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'voucherValidDays' : IDL.Nat,
  'tenantId' : TenantId,
  'voucherValue' : IDL.Nat,
  'termsUrl' : IDL.Text,
  'startDate' : IDL.Text,
});
export const Result_3 = IDL.Variant({
  'ok' : RegistrationPromo,
  'err' : IDL.Text,
});
export const SalesTier = IDL.Record({
  'minSales' : IDL.Nat,
  'voucherValue' : IDL.Nat,
});
export const SalesPromo = IDL.Record({
  'active' : IDL.Bool,
  'endDate' : IDL.Text,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'voucherValidDays' : IDL.Nat,
  'tenantId' : TenantId,
  'weeklyTiers' : IDL.Vec(SalesTier),
  'enabledCounter' : IDL.Bool,
  'monthlyTiers' : IDL.Vec(SalesTier),
  'termsUrl' : IDL.Text,
  'startDate' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : SalesPromo, 'err' : IDL.Text });
export const Timestamp = IDL.Nat;
export const Tenant = IDL.Record({
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'slug' : IDL.Text,
  'tenantId' : TenantId,
  'updatedAt' : Timestamp,
  'logoUrl' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
  'taxCode' : IDL.Text,
  'brandColor' : IDL.Text,
});
export const Result_7 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const RestaurantId = IDL.Text;
export const PendingActivation = IDL.Record({
  'expiresAt' : IDL.Int,
  'code' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : DeviceRole,
  'used' : IDL.Bool,
  'tenantId' : TenantId,
  'restaurantId' : IDL.Text,
});
export const Result_15 = IDL.Variant({
  'ok' : PendingActivation,
  'err' : IDL.Text,
});
export const OrderStatus = IDL.Record({
  'paymentStatus' : PaymentStatus,
  'tingeeQrCode' : IDL.Text,
  'invoiceId' : IDL.Text,
  'sharedLink' : IDL.Text,
  'bookingStatus' : BookingStatus,
  'pdfUrl' : IDL.Text,
  'tingeeQrId' : IDL.Text,
  'invoiceStatus' : InvoiceStatus,
});
export const Result_14 = IDL.Variant({ 'ok' : OrderStatus, 'err' : IDL.Text });
export const StoreHours = IDL.Record({
  'closeMinute' : IDL.Nat,
  'closeHour' : IDL.Nat,
  'openMinute' : IDL.Nat,
  'openHour' : IDL.Nat,
});
export const MenuEntry = IDL.Record({ 'itemId' : IDL.Text, 'menu' : MenuItem });
export const OrderId = IDL.Text;
export const OrderEntry = IDL.Record({ 'order' : Order, 'orderId' : OrderId });
export const RestaurantEntry = IDL.Record({
  'restaurantId' : IDL.Text,
  'restaurant' : Restaurant,
});
export const RestaurantMenuOverrideEntry = IDL.Record({
  'restaurantId' : IDL.Text,
  'overrides' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});
export const DeviceEntry = IDL.Record({
  'device' : Device,
  'deviceId' : IDL.Text,
});
export const PendingActivationEntry = IDL.Record({
  'code' : IDL.Text,
  'activation' : PendingActivation,
});
export const UpgradeState = IDL.Record({
  'menus' : IDL.Vec(MenuEntry),
  'orders' : IDL.Vec(OrderEntry),
  'restaurants' : IDL.Vec(RestaurantEntry),
  'restaurantMenuOverrides' : IDL.Vec(RestaurantMenuOverrideEntry),
  'devices' : IDL.Vec(DeviceEntry),
  'pendingActivations' : IDL.Vec(PendingActivationEntry),
});
export const Email = IDL.Text;
export const Result_13 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
export const Voucher = IDL.Record({
  'endDate' : IDL.Text,
  'value' : IDL.Nat,
  'code' : IDL.Text,
  'used' : IDL.Bool,
  'email' : IDL.Text,
  'tenantId' : TenantId,
  'programCode' : IDL.Text,
  'issuedAt' : IDL.Int,
  'startDate' : IDL.Text,
});
export const Result_12 = IDL.Variant({
  'ok' : IDL.Opt(Voucher),
  'err' : IDL.Text,
});
export const Result_11 = IDL.Variant({
  'ok' : IDL.Vec(Promotion),
  'err' : IDL.Text,
});
export const Result_10 = IDL.Variant({
  'ok' : IDL.Vec(RegistrationPromo),
  'err' : IDL.Text,
});
export const Result_9 = IDL.Variant({
  'ok' : IDL.Vec(SalesPromo),
  'err' : IDL.Text,
});
export const SendCodeResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Text,
});
export const VerifyResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_18], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'activateDevice' : IDL.Func(
      [IDL.Text, DeviceId, IDL.Text, IDL.Text],
      [Result_8],
      [],
    ),
  'addItem' : IDL.Func(
      [
        TenantId,
        DeviceId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Nat8),
      ],
      [Result_5],
      [],
    ),
  'addRestaurant' : IDL.Func(
      [
        TenantId,
        DeviceId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
      ],
      [Result_2],
      [],
    ),
  'applyPromotion' : IDL.Func(
      [TenantId, IDL.Text, IDL.Nat, Hmac],
      [Result_16],
      [],
    ),
  'applyPromotionCounter' : IDL.Func(
      [TenantId, IDL.Nat, Hmac],
      [Result_16],
      [],
    ),
  'applyVoucher' : IDL.Func(
      [TenantId, IDL.Text, IDL.Text, IDL.Nat, Hmac],
      [Result_6],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'callerHasEnterpriseRole' : IDL.Func(
      [DeviceId, TenantId, EnterpriseRole],
      [IDL.Bool],
      ['query'],
    ),
  'cancelOrder' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'changeOrderRestaurant' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'claimOrderEmail' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
  'cleanupExpiredActivations' : IDL.Func([], [IDL.Nat], []),
  'cleanupOrderByDevice' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'countVouchersByProgram' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Nat],
      ['query'],
    ),
  'createOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(OrderItem),
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [Result],
      [],
    ),
  'createPromotion' : IDL.Func(
      [
        TenantId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Bool),
        IDL.Vec(TimeSlot),
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(DiscountTier),
        IDL.Text,
      ],
      [Result_4],
      [],
    ),
  'createRegistrationPromo' : IDL.Func(
      [
        TenantId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [Result_3],
      [],
    ),
  'createSalesPromo' : IDL.Func(
      [
        TenantId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(SalesTier),
        IDL.Vec(SalesTier),
        IDL.Nat,
        IDL.Text,
      ],
      [Result_1],
      [],
    ),
  'createTenant' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Variant({ 'ok' : Tenant, 'err' : IDL.Text })],
      [],
    ),
  'deactivateExpiredPromotions' : IDL.Func([Hmac], [Result_6], []),
  'deleteItem' : IDL.Func([TenantId, DeviceId, IDL.Text], [Result_7], []),
  'deletePromotion' : IDL.Func([TenantId, IDL.Text, IDL.Text], [Result_7], []),
  'deleteRegistrationPromo' : IDL.Func(
      [TenantId, IDL.Text, IDL.Text],
      [Result_7],
      [],
    ),
  'deleteRestaurant' : IDL.Func([TenantId, DeviceId, IDL.Text], [Result_7], []),
  'deleteSalesPromo' : IDL.Func([TenantId, IDL.Text, IDL.Text], [Result_7], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'generateActivationCode' : IDL.Func(
      [TenantId, RestaurantId, DeviceRole, DeviceId],
      [Result_15],
      [],
    ),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanisterIdText' : IDL.Func([], [IDL.Text], ['query']),
  'getCurrentPromotion' : IDL.Func([TenantId], [IDL.Opt(Promotion)], ['query']),
  'getCurrentRegistrationPromo' : IDL.Func(
      [TenantId],
      [IDL.Opt(RegistrationPromo)],
      ['query'],
    ),
  'getCurrentSalesPromo' : IDL.Func(
      [TenantId],
      [IDL.Opt(SalesPromo)],
      ['query'],
    ),
  'getItemImage' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  'getKmDailyCount' : IDL.Func([TenantId, IDL.Text], [IDL.Nat], ['query']),
  'getKmUsageCount' : IDL.Func(
      [TenantId, IDL.Text, IDL.Text],
      [IDL.Nat],
      ['query'],
    ),
  'getMenu' : IDL.Func([TenantId], [IDL.Vec(MenuItem)], ['query']),
  'getMenuForRestaurant' : IDL.Func(
      [TenantId, IDL.Text],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
  'getOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [Result_14], ['query']),
  'getOrdersByEmail' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(Order)],
      [],
    ),
  'getPaymentMode' : IDL.Func([TenantId], [IDL.Text], ['query']),
  'getPromotionByCode' : IDL.Func(
      [TenantId, IDL.Text],
      [IDL.Opt(Promotion)],
      ['query'],
    ),
  'getRestaurants' : IDL.Func([TenantId], [IDL.Vec(Restaurant)], ['query']),
  'getStoreHours' : IDL.Func([TenantId], [StoreHours], ['query']),
  'getTenant' : IDL.Func([TenantId], [IDL.Opt(Tenant)], ['query']),
  'getTenantBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Tenant)], ['query']),
  'getUpgradeState' : IDL.Func([], [UpgradeState], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEmailVerified' : IDL.Func([Email], [IDL.Bool], ['query']),
  'isPromotionUsed' : IDL.Func(
      [TenantId, IDL.Text, IDL.Text],
      [Result_13],
      ['query'],
    ),
  'isRegistrationPromoUsed' : IDL.Func(
      [TenantId, IDL.Text, IDL.Text],
      [Result_13],
      ['query'],
    ),
  'isSalesPromoUsed' : IDL.Func(
      [TenantId, IDL.Text, IDL.Text],
      [Result_13],
      ['query'],
    ),
  'isStoreOpen' : IDL.Func([TenantId], [IDL.Bool], ['query']),
  'issueInvoiceByDevice' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'issueSalesBonus' : IDL.Func(
      [TenantId, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, Hmac],
      [Result_12],
      [],
    ),
  'listDevicesByRestaurant' : IDL.Func(
      [TenantId, RestaurantId],
      [IDL.Vec(Device)],
      ['query'],
    ),
  'listDevicesByRole' : IDL.Func(
      [TenantId, DeviceRole],
      [IDL.Vec(Device)],
      ['query'],
    ),
  'listMenus' : IDL.Func([TenantId], [IDL.Vec(MenuItem)], ['query']),
  'listMyVouchers' : IDL.Func(
      [TenantId, IDL.Text],
      [IDL.Vec(Voucher)],
      ['query'],
    ),
  'listOrders' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Order)], []),
  'listPaidOrdersForPickup' : IDL.Func([], [IDL.Vec(Order)], []),
  'listPendingPaymentOrders' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Order)],
      [],
    ),
  'listPromotions' : IDL.Func([TenantId, IDL.Text], [Result_11], ['query']),
  'listRegistrationPromos' : IDL.Func(
      [TenantId, IDL.Text],
      [Result_10],
      ['query'],
    ),
  'listRestaurants' : IDL.Func([TenantId], [IDL.Vec(Restaurant)], ['query']),
  'listSalesPromos' : IDL.Func([TenantId, IDL.Text], [Result_9], ['query']),
  'listTenants' : IDL.Func([IDL.Bool], [IDL.Vec(Tenant)], ['query']),
  'markPaymentExpired' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'markPickedUp' : IDL.Func([IDL.Text], [Result], []),
  'pruneOldOrdersNow' : IDL.Func([IDL.Text], [Result_6], []),
  'restoreUpgradeState' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Bool], []),
  'revokeDevice' : IDL.Func([TenantId, DeviceId, DeviceId], [Result_8], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'seedMenuItems' : IDL.Func([TenantId, DeviceId], [IDL.Bool], []),
  'sendKmNotifyEmails' : IDL.Func(
      [IDL.Vec(IDL.Text), IDL.Text, IDL.Text, Hmac],
      [Result_7],
      [],
    ),
  'sendVerificationCode' : IDL.Func([Email], [SendCodeResult], []),
  'setItemVisible' : IDL.Func(
      [TenantId, DeviceId, IDL.Text, IDL.Bool],
      [Result_5],
      [],
    ),
  'setPaymentMode' : IDL.Func([TenantId, IDL.Text], [Result_7], []),
  'setRestaurantPriceOverride' : IDL.Func(
      [TenantId, DeviceId, IDL.Text, IDL.Text, IDL.Nat],
      [Result_7],
      [],
    ),
  'setStoreHours' : IDL.Func([TenantId, StoreHours], [Result_7], []),
  'setTenantActive' : IDL.Func(
      [TenantId, IDL.Bool],
      [IDL.Variant({ 'ok' : Tenant, 'err' : IDL.Text })],
      [],
    ),
  'setVpsSecret' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'snapshotUpgradeState' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'stopPromotion' : IDL.Func([TenantId, IDL.Text, IDL.Text], [Result_4], []),
  'stopRegistrationPromo' : IDL.Func(
      [TenantId, IDL.Text, IDL.Text],
      [Result_3],
      [],
    ),
  'stopSalesPromo' : IDL.Func([TenantId, IDL.Text, IDL.Text], [Result_1], []),
  'tryConsumeKmSlot' : IDL.Func(
      [TenantId, IDL.Text, IDL.Text, IDL.Nat, Hmac],
      [Result_6],
      [],
    ),
  'updateInvoiceStatus' : IDL.Func(
      [OrderId, InvoiceStatus, IDL.Text, IDL.Text, Hmac],
      [Result],
      [],
    ),
  'updateItem' : IDL.Func(
      [
        TenantId,
        DeviceId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Nat8),
        IDL.Bool,
      ],
      [Result_5],
      [],
    ),
  'updateOrderQr' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat64),
        IDL.Text,
      ],
      [Result],
      [],
    ),
  'updatePaymentStatus' : IDL.Func(
      [OrderId, PaymentStatus, Hmac],
      [Result],
      [],
    ),
  'updatePromotion' : IDL.Func(
      [
        TenantId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Bool),
        IDL.Vec(TimeSlot),
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(DiscountTier),
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
      ],
      [Result_4],
      [],
    ),
  'updateRegistrationPromo' : IDL.Func(
      [
        TenantId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Bool,
        IDL.Text,
      ],
      [Result_3],
      [],
    ),
  'updateRestaurant' : IDL.Func(
      [
        TenantId,
        DeviceId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Float64,
        IDL.Float64,
      ],
      [Result_2],
      [],
    ),
  'updateSalesPromo' : IDL.Func(
      [
        TenantId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(SalesTier),
        IDL.Vec(SalesTier),
        IDL.Nat,
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
      ],
      [Result_1],
      [],
    ),
  'updateStatus' : IDL.Func([OrderId, BookingStatus, Hmac], [Result], []),
  'updateTenant' : IDL.Func(
      [
        TenantId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Variant({ 'ok' : Tenant, 'err' : IDL.Text })],
      [],
    ),
  'verifyEmailCode' : IDL.Func([IDL.Text, Email, IDL.Text], [VerifyResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_18 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const DeviceId = IDL.Text;
  const DeviceRole = IDL.Variant({
    'accounting' : IDL.Null,
    'paymentQueue' : IDL.Null,
    'admin' : IDL.Null,
    'salesPromoReporting' : IDL.Null,
    'cashier' : IDL.Null,
    'tenantAdmin' : IDL.Null,
    'driver' : IDL.Null,
  });
  const TenantId = IDL.Text;
  const Device = IDL.Record({
    'active' : IDL.Bool,
    'activatedAt' : IDL.Int,
    'name' : IDL.Text,
    'role' : DeviceRole,
    'tenantId' : TenantId,
    'restaurantId' : IDL.Text,
    'deviceId' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Result_8 = IDL.Variant({ 'ok' : Device, 'err' : IDL.Text });
  const MenuItem = IDL.Record({
    'itemId' : IDL.Text,
    'name' : IDL.Text,
    'tenantId' : TenantId,
    'visible' : IDL.Bool,
    'category' : IDL.Text,
    'image' : IDL.Vec(IDL.Nat8),
    'price' : IDL.Nat,
    'vatRate' : IDL.Nat,
    'unitName' : IDL.Text,
  });
  const Result_5 = IDL.Variant({ 'ok' : MenuItem, 'err' : IDL.Text });
  const Restaurant = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'name' : IDL.Text,
    'tenantId' : TenantId,
    'restaurantId' : IDL.Text,
    'address' : IDL.Text,
    'visible' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const Result_2 = IDL.Variant({ 'ok' : Restaurant, 'err' : IDL.Text });
  const Hmac = IDL.Text;
  const Result_16 = IDL.Variant({
    'ok' : IDL.Record({
      'discountAmount' : IDL.Nat,
      'promotionCode' : IDL.Text,
    }),
    'err' : IDL.Text,
  });
  const Result_6 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EnterpriseRole = IDL.Variant({
    'accounting' : IDL.Null,
    'paymentQueue' : IDL.Null,
    'salesPromoReporting' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'expired' : IDL.Null,
    'paid' : IDL.Null,
    'refunded' : IDL.Null,
    'unpaid' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'shipping' : IDL.Null,
    'pickedUp' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'itemId' : IDL.Text,
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'vatRate' : IDL.Nat,
    'unitName' : IDL.Text,
  });
  const InvoiceStatus = IDL.Variant({
    'none' : IDL.Null,
    'invoiced' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Order = IDL.Record({
    'paymentStatus' : PaymentStatus,
    'cusTaxCode' : IDL.Text,
    'cusName' : IDL.Text,
    'createdAt' : IDL.Int,
    'taxTotal' : IDL.Nat,
    'ahamoveOrderId' : IDL.Text,
    'tingeeQrCode' : IDL.Text,
    'shippingFee' : IDL.Nat,
    'invoiceId' : IDL.Text,
    'sharedLink' : IDL.Text,
    'cusPhone' : IDL.Text,
    'tenantId' : TenantId,
    'orderId' : IDL.Text,
    'restaurantId' : IDL.Text,
    'updatedAt' : IDL.Int,
    'bookingStatus' : BookingStatus,
    'receiverEmail' : IDL.Text,
    'pickupCode' : IDL.Text,
    'expireAt' : IDL.Opt(IDL.Nat64),
    'kmDiscountAmount' : IDL.Nat,
    'pdfUrl' : IDL.Text,
    'tingeeQrId' : IDL.Text,
    'goodsAmount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
    'voucherDiscountAmount' : IDL.Nat,
    'amount' : IDL.Nat,
    'paymentVerificationImage' : IDL.Text,
    'cusAddress' : IDL.Text,
    'invoiceStatus' : InvoiceStatus,
    'billId' : IDL.Opt(IDL.Text),
    'qrCode' : IDL.Opt(IDL.Text),
  });
  const Result = IDL.Variant({ 'ok' : Order, 'err' : IDL.Text });
  const TimeSlot = IDL.Record({
    'durationMinutes' : IDL.Nat,
    'startMinute' : IDL.Nat,
    'startHour' : IDL.Nat,
  });
  const DiscountTier = IDL.Record({
    'discountAmount' : IDL.Nat,
    'minOrderValue' : IDL.Nat,
  });
  const Promotion = IDL.Record({
    'tiers' : IDL.Vec(DiscountTier),
    'active' : IDL.Bool,
    'endDate' : IDL.Text,
    'timeSlots' : IDL.Vec(TimeSlot),
    'enabledOnline' : IDL.Bool,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'daysOfWeek' : IDL.Vec(IDL.Bool),
    'tenantId' : TenantId,
    'enabledCounter' : IDL.Bool,
    'dailyOrderLimit' : IDL.Nat,
    'perCustomerDailyLimit' : IDL.Nat,
    'termsUrl' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const Result_4 = IDL.Variant({ 'ok' : Promotion, 'err' : IDL.Text });
  const RegistrationPromo = IDL.Record({
    'active' : IDL.Bool,
    'endDate' : IDL.Text,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'voucherValidDays' : IDL.Nat,
    'tenantId' : TenantId,
    'voucherValue' : IDL.Nat,
    'termsUrl' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const Result_3 = IDL.Variant({ 'ok' : RegistrationPromo, 'err' : IDL.Text });
  const SalesTier = IDL.Record({
    'minSales' : IDL.Nat,
    'voucherValue' : IDL.Nat,
  });
  const SalesPromo = IDL.Record({
    'active' : IDL.Bool,
    'endDate' : IDL.Text,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'voucherValidDays' : IDL.Nat,
    'tenantId' : TenantId,
    'weeklyTiers' : IDL.Vec(SalesTier),
    'enabledCounter' : IDL.Bool,
    'monthlyTiers' : IDL.Vec(SalesTier),
    'termsUrl' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'ok' : SalesPromo, 'err' : IDL.Text });
  const Timestamp = IDL.Nat;
  const Tenant = IDL.Record({
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'slug' : IDL.Text,
    'tenantId' : TenantId,
    'updatedAt' : Timestamp,
    'logoUrl' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
    'taxCode' : IDL.Text,
    'brandColor' : IDL.Text,
  });
  const Result_7 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const RestaurantId = IDL.Text;
  const PendingActivation = IDL.Record({
    'expiresAt' : IDL.Int,
    'code' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : DeviceRole,
    'used' : IDL.Bool,
    'tenantId' : TenantId,
    'restaurantId' : IDL.Text,
  });
  const Result_15 = IDL.Variant({ 'ok' : PendingActivation, 'err' : IDL.Text });
  const OrderStatus = IDL.Record({
    'paymentStatus' : PaymentStatus,
    'tingeeQrCode' : IDL.Text,
    'invoiceId' : IDL.Text,
    'sharedLink' : IDL.Text,
    'bookingStatus' : BookingStatus,
    'pdfUrl' : IDL.Text,
    'tingeeQrId' : IDL.Text,
    'invoiceStatus' : InvoiceStatus,
  });
  const Result_14 = IDL.Variant({ 'ok' : OrderStatus, 'err' : IDL.Text });
  const StoreHours = IDL.Record({
    'closeMinute' : IDL.Nat,
    'closeHour' : IDL.Nat,
    'openMinute' : IDL.Nat,
    'openHour' : IDL.Nat,
  });
  const MenuEntry = IDL.Record({ 'itemId' : IDL.Text, 'menu' : MenuItem });
  const OrderId = IDL.Text;
  const OrderEntry = IDL.Record({ 'order' : Order, 'orderId' : OrderId });
  const RestaurantEntry = IDL.Record({
    'restaurantId' : IDL.Text,
    'restaurant' : Restaurant,
  });
  const RestaurantMenuOverrideEntry = IDL.Record({
    'restaurantId' : IDL.Text,
    'overrides' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  const DeviceEntry = IDL.Record({ 'device' : Device, 'deviceId' : IDL.Text });
  const PendingActivationEntry = IDL.Record({
    'code' : IDL.Text,
    'activation' : PendingActivation,
  });
  const UpgradeState = IDL.Record({
    'menus' : IDL.Vec(MenuEntry),
    'orders' : IDL.Vec(OrderEntry),
    'restaurants' : IDL.Vec(RestaurantEntry),
    'restaurantMenuOverrides' : IDL.Vec(RestaurantMenuOverrideEntry),
    'devices' : IDL.Vec(DeviceEntry),
    'pendingActivations' : IDL.Vec(PendingActivationEntry),
  });
  const Email = IDL.Text;
  const Result_13 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  const Voucher = IDL.Record({
    'endDate' : IDL.Text,
    'value' : IDL.Nat,
    'code' : IDL.Text,
    'used' : IDL.Bool,
    'email' : IDL.Text,
    'tenantId' : TenantId,
    'programCode' : IDL.Text,
    'issuedAt' : IDL.Int,
    'startDate' : IDL.Text,
  });
  const Result_12 = IDL.Variant({ 'ok' : IDL.Opt(Voucher), 'err' : IDL.Text });
  const Result_11 = IDL.Variant({
    'ok' : IDL.Vec(Promotion),
    'err' : IDL.Text,
  });
  const Result_10 = IDL.Variant({
    'ok' : IDL.Vec(RegistrationPromo),
    'err' : IDL.Text,
  });
  const Result_9 = IDL.Variant({
    'ok' : IDL.Vec(SalesPromo),
    'err' : IDL.Text,
  });
  const SendCodeResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const VerifyResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_18], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'activateDevice' : IDL.Func(
        [IDL.Text, DeviceId, IDL.Text, IDL.Text],
        [Result_8],
        [],
      ),
    'addItem' : IDL.Func(
        [
          TenantId,
          DeviceId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Nat8),
        ],
        [Result_5],
        [],
      ),
    'addRestaurant' : IDL.Func(
        [
          TenantId,
          DeviceId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
        ],
        [Result_2],
        [],
      ),
    'applyPromotion' : IDL.Func(
        [TenantId, IDL.Text, IDL.Nat, Hmac],
        [Result_16],
        [],
      ),
    'applyPromotionCounter' : IDL.Func(
        [TenantId, IDL.Nat, Hmac],
        [Result_16],
        [],
      ),
    'applyVoucher' : IDL.Func(
        [TenantId, IDL.Text, IDL.Text, IDL.Nat, Hmac],
        [Result_6],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'callerHasEnterpriseRole' : IDL.Func(
        [DeviceId, TenantId, EnterpriseRole],
        [IDL.Bool],
        ['query'],
      ),
    'cancelOrder' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'changeOrderRestaurant' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'claimOrderEmail' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
    'cleanupExpiredActivations' : IDL.Func([], [IDL.Nat], []),
    'cleanupOrderByDevice' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'countVouchersByProgram' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Nat],
        ['query'],
      ),
    'createOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(OrderItem),
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [Result],
        [],
      ),
    'createPromotion' : IDL.Func(
        [
          TenantId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Bool),
          IDL.Vec(TimeSlot),
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(DiscountTier),
          IDL.Text,
        ],
        [Result_4],
        [],
      ),
    'createRegistrationPromo' : IDL.Func(
        [
          TenantId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [Result_3],
        [],
      ),
    'createSalesPromo' : IDL.Func(
        [
          TenantId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(SalesTier),
          IDL.Vec(SalesTier),
          IDL.Nat,
          IDL.Text,
        ],
        [Result_1],
        [],
      ),
    'createTenant' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Variant({ 'ok' : Tenant, 'err' : IDL.Text })],
        [],
      ),
    'deactivateExpiredPromotions' : IDL.Func([Hmac], [Result_6], []),
    'deleteItem' : IDL.Func([TenantId, DeviceId, IDL.Text], [Result_7], []),
    'deletePromotion' : IDL.Func(
        [TenantId, IDL.Text, IDL.Text],
        [Result_7],
        [],
      ),
    'deleteRegistrationPromo' : IDL.Func(
        [TenantId, IDL.Text, IDL.Text],
        [Result_7],
        [],
      ),
    'deleteRestaurant' : IDL.Func(
        [TenantId, DeviceId, IDL.Text],
        [Result_7],
        [],
      ),
    'deleteSalesPromo' : IDL.Func(
        [TenantId, IDL.Text, IDL.Text],
        [Result_7],
        [],
      ),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'generateActivationCode' : IDL.Func(
        [TenantId, RestaurantId, DeviceRole, DeviceId],
        [Result_15],
        [],
      ),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanisterIdText' : IDL.Func([], [IDL.Text], ['query']),
    'getCurrentPromotion' : IDL.Func(
        [TenantId],
        [IDL.Opt(Promotion)],
        ['query'],
      ),
    'getCurrentRegistrationPromo' : IDL.Func(
        [TenantId],
        [IDL.Opt(RegistrationPromo)],
        ['query'],
      ),
    'getCurrentSalesPromo' : IDL.Func(
        [TenantId],
        [IDL.Opt(SalesPromo)],
        ['query'],
      ),
    'getItemImage' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getKmDailyCount' : IDL.Func([TenantId, IDL.Text], [IDL.Nat], ['query']),
    'getKmUsageCount' : IDL.Func(
        [TenantId, IDL.Text, IDL.Text],
        [IDL.Nat],
        ['query'],
      ),
    'getMenu' : IDL.Func([TenantId], [IDL.Vec(MenuItem)], ['query']),
    'getMenuForRestaurant' : IDL.Func(
        [TenantId, IDL.Text],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
    'getOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [Result_14], ['query']),
    'getOrdersByEmail' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(Order)],
        [],
      ),
    'getPaymentMode' : IDL.Func([TenantId], [IDL.Text], ['query']),
    'getPromotionByCode' : IDL.Func(
        [TenantId, IDL.Text],
        [IDL.Opt(Promotion)],
        ['query'],
      ),
    'getRestaurants' : IDL.Func([TenantId], [IDL.Vec(Restaurant)], ['query']),
    'getStoreHours' : IDL.Func([TenantId], [StoreHours], ['query']),
    'getTenant' : IDL.Func([TenantId], [IDL.Opt(Tenant)], ['query']),
    'getTenantBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Tenant)], ['query']),
    'getUpgradeState' : IDL.Func([], [UpgradeState], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEmailVerified' : IDL.Func([Email], [IDL.Bool], ['query']),
    'isPromotionUsed' : IDL.Func(
        [TenantId, IDL.Text, IDL.Text],
        [Result_13],
        ['query'],
      ),
    'isRegistrationPromoUsed' : IDL.Func(
        [TenantId, IDL.Text, IDL.Text],
        [Result_13],
        ['query'],
      ),
    'isSalesPromoUsed' : IDL.Func(
        [TenantId, IDL.Text, IDL.Text],
        [Result_13],
        ['query'],
      ),
    'isStoreOpen' : IDL.Func([TenantId], [IDL.Bool], ['query']),
    'issueInvoiceByDevice' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'issueSalesBonus' : IDL.Func(
        [TenantId, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, Hmac],
        [Result_12],
        [],
      ),
    'listDevicesByRestaurant' : IDL.Func(
        [TenantId, RestaurantId],
        [IDL.Vec(Device)],
        ['query'],
      ),
    'listDevicesByRole' : IDL.Func(
        [TenantId, DeviceRole],
        [IDL.Vec(Device)],
        ['query'],
      ),
    'listMenus' : IDL.Func([TenantId], [IDL.Vec(MenuItem)], ['query']),
    'listMyVouchers' : IDL.Func(
        [TenantId, IDL.Text],
        [IDL.Vec(Voucher)],
        ['query'],
      ),
    'listOrders' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Order)], []),
    'listPaidOrdersForPickup' : IDL.Func([], [IDL.Vec(Order)], []),
    'listPendingPaymentOrders' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Order)],
        [],
      ),
    'listPromotions' : IDL.Func([TenantId, IDL.Text], [Result_11], ['query']),
    'listRegistrationPromos' : IDL.Func(
        [TenantId, IDL.Text],
        [Result_10],
        ['query'],
      ),
    'listRestaurants' : IDL.Func([TenantId], [IDL.Vec(Restaurant)], ['query']),
    'listSalesPromos' : IDL.Func([TenantId, IDL.Text], [Result_9], ['query']),
    'listTenants' : IDL.Func([IDL.Bool], [IDL.Vec(Tenant)], ['query']),
    'markPaymentExpired' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'markPickedUp' : IDL.Func([IDL.Text], [Result], []),
    'pruneOldOrdersNow' : IDL.Func([IDL.Text], [Result_6], []),
    'restoreUpgradeState' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Bool], []),
    'revokeDevice' : IDL.Func([TenantId, DeviceId, DeviceId], [Result_8], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'seedMenuItems' : IDL.Func([TenantId, DeviceId], [IDL.Bool], []),
    'sendKmNotifyEmails' : IDL.Func(
        [IDL.Vec(IDL.Text), IDL.Text, IDL.Text, Hmac],
        [Result_7],
        [],
      ),
    'sendVerificationCode' : IDL.Func([Email], [SendCodeResult], []),
    'setItemVisible' : IDL.Func(
        [TenantId, DeviceId, IDL.Text, IDL.Bool],
        [Result_5],
        [],
      ),
    'setPaymentMode' : IDL.Func([TenantId, IDL.Text], [Result_7], []),
    'setRestaurantPriceOverride' : IDL.Func(
        [TenantId, DeviceId, IDL.Text, IDL.Text, IDL.Nat],
        [Result_7],
        [],
      ),
    'setStoreHours' : IDL.Func([TenantId, StoreHours], [Result_7], []),
    'setTenantActive' : IDL.Func(
        [TenantId, IDL.Bool],
        [IDL.Variant({ 'ok' : Tenant, 'err' : IDL.Text })],
        [],
      ),
    'setVpsSecret' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'snapshotUpgradeState' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'stopPromotion' : IDL.Func([TenantId, IDL.Text, IDL.Text], [Result_4], []),
    'stopRegistrationPromo' : IDL.Func(
        [TenantId, IDL.Text, IDL.Text],
        [Result_3],
        [],
      ),
    'stopSalesPromo' : IDL.Func([TenantId, IDL.Text, IDL.Text], [Result_1], []),
    'tryConsumeKmSlot' : IDL.Func(
        [TenantId, IDL.Text, IDL.Text, IDL.Nat, Hmac],
        [Result_6],
        [],
      ),
    'updateInvoiceStatus' : IDL.Func(
        [OrderId, InvoiceStatus, IDL.Text, IDL.Text, Hmac],
        [Result],
        [],
      ),
    'updateItem' : IDL.Func(
        [
          TenantId,
          DeviceId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Nat8),
          IDL.Bool,
        ],
        [Result_5],
        [],
      ),
    'updateOrderQr' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat64),
          IDL.Text,
        ],
        [Result],
        [],
      ),
    'updatePaymentStatus' : IDL.Func(
        [OrderId, PaymentStatus, Hmac],
        [Result],
        [],
      ),
    'updatePromotion' : IDL.Func(
        [
          TenantId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Bool),
          IDL.Vec(TimeSlot),
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(DiscountTier),
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
        ],
        [Result_4],
        [],
      ),
    'updateRegistrationPromo' : IDL.Func(
        [
          TenantId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Bool,
          IDL.Text,
        ],
        [Result_3],
        [],
      ),
    'updateRestaurant' : IDL.Func(
        [
          TenantId,
          DeviceId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Float64,
          IDL.Float64,
        ],
        [Result_2],
        [],
      ),
    'updateSalesPromo' : IDL.Func(
        [
          TenantId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(SalesTier),
          IDL.Vec(SalesTier),
          IDL.Nat,
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
        ],
        [Result_1],
        [],
      ),
    'updateStatus' : IDL.Func([OrderId, BookingStatus, Hmac], [Result], []),
    'updateTenant' : IDL.Func(
        [
          TenantId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Variant({ 'ok' : Tenant, 'err' : IDL.Text })],
        [],
      ),
    'verifyEmailCode' : IDL.Func(
        [IDL.Text, Email, IDL.Text],
        [VerifyResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };